stages:
  raw_descriptives:
    cmd: papermill pipeline/01-basic_descriptives.ipynb reports/notebooks/01-basic_descriptives.ipynb
    deps:
      - pipeline/01-basic_descriptives.ipynb
      - src/load.py
      - data/raw/
    outs:
      - reports/notebooks/01-basic_descriptives.ipynb
      - reports/tables/raw_descriptives.csv
  preprocess:
    cmd: python pipeline/02-preprocess.py
    deps:
      - pipeline/02-preprocess.py
      - data/raw
    outs:
      - data/interim/interim.parquet
  run_model:
    cmd: Rscript pipeline/03-run_model.R
    deps:
      - pipeline/03-run_model.R
      - data/interim/interim.parquet
    outs:
      - data/models/model.RDS
  plot_results:
    cmd: Rscript -e "rmarkdown::render('pipeline/04-plot_results.Rmd', 'html_document', '../reports/notebooks/04-plot_results.html')" 
    deps:
      - pipeline/04-plot_results.Rmd
      - data/models/model.RDS
    outs:
      - reports/figures/residuals.svg
      - reports/tables/regression_table.tex
      - reports/notebooks/04-plot_results.html
