---
title: "Regression Analysis"
output: html_document
---

```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo = TRUE)
options(box.path = here())

box::use(
  r / load
)
# box::reload(load)

library(stargazer)
library(tidyverse)
theme_set(theme_minimal())

model <- readRDS(here("data", "models", "model.RDS"))
```

```{r}
# stargazer(
#   model,
#   type = "text",
#   title = "Regression Results",
#   dep.var.labels = c("y"),
#   omit.stat = c("ser", "f"),
#   no.space = TRUE
# )
```

```{r}
tex_table <- stargazer(
  model,
  type = "latex",
  out = here("reports", "tables", "regression_table.tex"),
  title = "Regression Results",
  label = "tab:regression",
  dep.var.labels = c("y"),
  omit.stat = c("ser", "f"),
  no.space = TRUE
)
```

```{r}
df <- data.frame(
  fitted = fitted(model),
  residuals = resid(model)
)
```

```{r}
plot <- df |>
  ggplot(aes(x = fitted, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed")

plot
```

```{r}
ggsave(here("reports", "figures", "residuals.svg"), width = 5, height = 4)
```
